# MENT_START = '[MENT_START]'
# MENT_END = '[MENT_END]'
# COREF_START = '[COREF_START]'
# COREF_END = '[COREF_END]'

TOKENS = {
    'MENT_START': '[MENT_START]',
    'MENT_END': '[MENT_END]',
    'COREF_START': '[COREF_START]',
    'COREF_END': '[COREF_END]'
}

PAREN_TOKENS = {
    'MENT_START': '[',
    'MENT_END': ']',
    'COREF_START': '[',
    'COREF_END': ']'
}
